### PR TITLE
Publish 7.0.0

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by bvssvni** [comment]
Merging.

**Comment by phaazon** [comment]
I don’t really get why `7.0.0`. It could have been `6.0.1` as I just patched a bug, right?

**Comment by bvssvni** [comment]
@phaazon I think you are right. I saw this https://github.com/PistonDevelopers/wavefront_obj/commit/1c069d4665f8b642c194409cdf305911b430a620#diff-72dac0bc15578b7a7f1e37d8d65305dbR55 and bumped it to 7.0.0 to be safe.

**Comment by phaazon** [comment]
Hm, yeah, it’s public. I guess it should have been _minor_ then. I think it’s okay, it’s better to have a breaking change that doesn’t break anything than the other way around. :yum:

**Comment by bvssvni** [comment]
The rule is that the first non-zero number must be bumped when:

- there is a breaking change
- there is a bump in the first non-zero number of any dependencies

I am investigating whether we can add some attribute to deny `pub` when `pub(crate)` would suffice.

**Comment by bvssvni** [comment]
I found it: `#![deny(unreachable_pub)]`.

**Comment by phaazon** [comment]
I didn’t even know it existed. Very nice!

**Pull request merged**
